version: '3.1'

services:

  db:
    container_name: local-rss-agg
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: local-rss-agg
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      TZ: Asia/Bangkok
    ports:
      - 3450:5432

  adminer:
    container_name: rss-agg-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
